Repository Kajabi/sage, pull requests merged in 2020-04, with the labels that each got.

#133 Button: Tertiary & Button: Icon-Left/RIght
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_icon_button.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/button/_preview.html.erb
  app/views/sage/examples/elements/icon_button/_preview.html.erb
  app/views/sage/examples/elements/icon_button/_props.html.erb
  app/views/sage/examples/elements/icon_button/_rules_do.html.erb
  app/views/sage/examples/elements/icon_button/_rules_dont.html.erb
Labels: Review

#99 Card implementation
  app/assets/images/sage/card/card-placeholder-lg.png
  app/assets/images/sage/card/card-placeholder-sm.png
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/objects/_card.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/card/_preview.html.erb
  app/views/sage/examples/objects/card/_props.html.erb
  app/views/sage/examples/objects/card/_rules_do.html.erb
  app/views/sage/examples/objects/card/_rules_dont.html.erb
Labels: Review

#137 new description element
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/elements/_description.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/description/_preview.html.erb
  app/views/sage/examples/elements/description/_props.html.erb
  app/views/sage/examples/elements/description/_rules_do.html.erb
  app/views/sage/examples/elements/description/_rules_dont.html.erb
Labels: Review

#136 Live stream controls
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_control.scss
  app/assets/stylesheets/sage/system/vendor/_reboot.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/live_stream_control/_preview.html.erb
  app/views/sage/examples/objects/live_stream_control/_props.html.erb
  app/views/sage/examples/objects/live_stream_control/_rules_do.html.erb
  app/views/sage/examples/objects/live_stream_control/_rules_dont.html.erb
Labels: Review

#143 Button outline inconsistencies
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
Labels: Review, thumbsup

#141 Live stream wrapper
  app/assets/stylesheets/sage/docs/_colors.scss
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_live_stream_wrapper.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_control.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_footer.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_header.scss
  app/assets/stylesheets/sage/system/tokens/_color_palette.scss
  app/assets/stylesheets/sage/system/tokens/_shadow.scss
  app/helpers/sage/elements_helper.rb
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/elements/live_stream_wrapper/_preview.html.erb
  app/views/sage/examples/elements/live_stream_wrapper/_props.html.erb
  app/views/sage/examples/elements/live_stream_wrapper/_rules_do.html.erb
  app/views/sage/examples/elements/live_stream_wrapper/_rules_dont.html.erb
  app/views/sage/examples/objects/live_stream_footer/_preview.html.erb
  app/views/sage/examples/objects/live_stream_footer/_props.html.erb
  app/views/sage/examples/objects/live_stream_footer/_rules_do.html.erb
  app/views/sage/examples/objects/live_stream_footer/_rules_dont.html.erb
  app/views/sage/examples/objects/live_stream_header/_preview.html.erb
  app/views/sage/examples/objects/live_stream_header/_props.html.erb
  app/views/sage/examples/objects/live_stream_header/_rules_do.html.erb
  app/views/sage/examples/objects/live_stream_header/_rules_dont.html.erb
  app/views/sage/pages/color.html.erb
Labels: Review

#139 Revise input field and textarea label appearance
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
  app/views/sage/examples/elements/form_input/_preview.html.erb
  app/views/sage/examples/elements/form_input/_props.html.erb
  app/views/sage/examples/elements/form_input/_rules_do.html.erb
  app/views/sage/examples/elements/form_input/_rules_dont.html.erb
  app/views/sage/examples/elements/form_textarea/_preview.html.erb
Labels: Review, thumbsup

#124 [mobile] Loading examples overlapping
  app/assets/stylesheets/sage/docs/_example.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_loader.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/loader/_preview.html.erb
  app/views/sage/examples/elements/loader/_props.html.erb
  app/views/sage/examples/elements/loader/_rules_do.html.erb
  app/views/sage/examples/elements/loader/_rules_dont.html.erb
Labels: Review, mobile

#146 bumping version number
  lib/sage/version.rb
Labels: Review

#148 Add favicon, cleanup documentation structure
  app/assets/images/sage/apple-touch-icon.png
  app/assets/images/sage/favicon-16x16.png
  app/assets/images/sage/favicon-32x32.png
  app/assets/images/sage/favicon.ico
  app/assets/stylesheets/sage/docs/_example.scss
  app/views/layouts/sage/application.html.erb
  app/views/layouts/sage/breakout.html.erb
  app/views/sage/application/_meta.html.erb
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/elements/_element_preview.html.erb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/examples/objects/_object_preview.html.erb
  app/views/sage/pages/elements.html.erb
  app/views/sage/pages/objects.html.erb
  config/initializers/assets.rb
Labels: Review, enhancement

#150 updating the description size
  app/assets/stylesheets/sage/system/patterns/elements/_description.scss
Labels: Review

#129 Refactor sidebar JS as global module
  app/assets/javascripts/sage/docs/live-option-menu.js
  app/assets/javascripts/sage/sage_docs.js
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/define.js
  app/assets/javascripts/sage/system/overlay.js
  app/assets/javascripts/sage/system/sidebar.js
  app/assets/javascripts/sage/system/tooltip.js
  app/assets/javascripts/sage/system/util.js
  app/assets/stylesheets/sage/docs/_sidebar.scss
  app/assets/stylesheets/sage/sage_docs.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_overlay.scss
  app/assets/stylesheets/sage/system/patterns/objects/_sidebar.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/application/_assistant.html.erb
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/examples/objects/assistant/_preview.html.erb
  app/views/sage/examples/objects/assistant/_props.html.erb
  app/views/sage/examples/objects/sidebar/_preview.html.erb
  app/views/sage/examples/objects/sidebar/_props.html.erb
  app/views/sage/examples/objects/sidebar/_rules_do.html.erb
  app/views/sage/examples/objects/sidebar/_rules_dont.html.erb
Labels: Review

#151 changing to h3
  app/views/sage/examples/objects/form_section/_preview.html.erb
Labels: Review

#152 Update dependencies
  app/assets/javascripts/sage/system/sidebar.js
  package-lock.json
Labels: Review

#154 Quick Fix: Duplicate max-widths for containers.
  app/assets/stylesheets/sage/system/layout/_container.scss
Labels: Review, thumbsup

#127 [mobile] Tables overflowing container
  app/assets/stylesheets/sage/docs/_status_key.scss
  app/assets/stylesheets/sage/docs/_status_table.scss
  app/assets/stylesheets/sage/docs/_table.scss
  app/assets/stylesheets/sage/sage_docs.css.scss
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/table/_preview.html.erb
  app/views/sage/examples/elements/table/_props.html.erb
  app/views/sage/examples/elements/table/_rules_do.html.erb
  app/views/sage/examples/elements/table/_rules_dont.html.erb
  app/views/sage/pages/status.html.erb
Labels: Review, mobile, thumbsup

#155 Cleanup live components
  app/assets/stylesheets/sage/system/patterns/elements/_live_stream_wrapper.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_control.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_footer.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_header.scss
  app/views/sage/examples/objects/live_stream_control/_markup.html.erb
  app/views/sage/examples/objects/live_stream_control/_preview.html.erb
  app/views/sage/examples/objects/live_stream_footer/_markup.html.erb
  app/views/sage/examples/objects/live_stream_footer/_preview.html.erb
  app/views/sage/examples/objects/live_stream_header/_markup.html.erb
  app/views/sage/examples/objects/live_stream_header/_preview.html.erb
Labels: Review

#158 Revise tables in documentation to use `.sage-table` styling
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/views/sage/application/_status_item.html.erb
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/objects/_object.html.erb
Labels: Review, documentation

#162 Tighten icon use and documentation.
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/views/sage/examples/objects/live_user_control/_preview.html.erb
  app/views/sage/examples/objects/page_heading/_preview.html.erb
  app/views/sage/pages/icon.html.erb
Labels: Review

#160 Live avatar adjustments
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/views/sage/examples/objects/live_avatar/_markup.html.erb
  app/views/sage/examples/objects/live_avatar/_preview.html.erb
  app/views/sage/examples/objects/live_profile_card/_markup.html.erb
  app/views/sage/examples/objects/live_profile_card/_preview.html.erb
Labels: Review

#163 Sage.init()
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/views/layouts/sage/application.html.erb
  app/views/layouts/sage/breakout.html.erb
  app/views/sage/application/_meta.html.erb
  app/views/sage/application/_scripts.html.erb
  app/views/sage/application/_styles.html.erb
Labels: Review

#86 Stylelint fixes and updated generator comment styles
  app/assets/stylesheets/sage/docs/_colors.scss
  app/assets/stylesheets/sage/docs/_icon.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/layout/_grid.scss
  app/assets/stylesheets/sage/system/layout/_page.scss
  app/assets/stylesheets/sage/system/patterns/elements/_checkbox.scss
  app/assets/stylesheets/sage/system/patterns/elements/_description.scss
  app/assets/stylesheets/sage/system/patterns/elements/_live_stream_wrapper.scss
  app/assets/stylesheets/sage/system/patterns/elements/_menu_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/assets/stylesheets/sage/system/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/system/patterns/objects/_form_section.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_control.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_footer.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_header.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_video_grid.scss
  app/assets/stylesheets/sage/system/patterns/objects/_page_heading.scss
  app/assets/stylesheets/sage/system/patterns/objects/_panel.scss
  app/assets/stylesheets/sage/system/vendor/_reboot.scss
  app/views/layouts/sage/application.html.erb
  app/views/sage/pages/icon.html.erb
  lib/generators/sage_element/templates/style.scss
  lib/generators/sage_object/templates/style.scss
  lib/generators/sage_token/templates/style.scss
  lib/generators/sage_utility/templates/style.scss
Labels: Review, documentation, thumbsup

#164 Complete Live video partials
  app/views/sage/examples/objects/live_stream_video_grid/_markup.html.erb
  app/views/sage/examples/objects/live_stream_video_grid/_preview.html.erb
Labels: Review, thumbsup

#166 Add live user control partial
  app/assets/javascripts/sage/docs/live-option-menu.js
  app/assets/stylesheets/sage/system/patterns/objects/_live_user_control.scss
  app/views/sage/examples/objects/live_option_menu/_markup.html.erb
  app/views/sage/examples/objects/live_option_menu/_preview.html.erb
  app/views/sage/examples/objects/live_profile_card/_markup.html.erb
  app/views/sage/examples/objects/live_user_control/_markup.html.erb
  app/views/sage/examples/objects/live_user_control/_preview.html.erb
Labels: Review, thumbsup

#165 Clean up `_colors.scss` CSS
  app/assets/stylesheets/sage/docs/_colors.scss
  app/views/sage/pages/_color_values.html.erb
  app/views/sage/pages/color.html.erb
Labels: Review, thumbsup

#170 Avatar video fallback
  app/assets/images/sage/avatar/alex.png
  app/assets/images/sage/avatar/chanel.png
  app/assets/images/sage/avatar/cj.png
  app/assets/images/sage/avatar/court.png
  app/assets/images/sage/avatar/forrest.png
  app/assets/images/sage/avatar/isabelle.png
  app/assets/images/sage/avatar/jay.png
  app/assets/images/sage/avatar/jj.png
  app/assets/images/sage/avatar/lienha.png
  app/assets/images/sage/avatar/phil.png
  app/assets/images/sage/avatar/sean.png
  app/assets/stylesheets/sage/system/patterns/elements/_live_stream_wrapper.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/views/sage/examples/objects/live_avatar/_preview.html.erb
  app/views/sage/examples/objects/live_profile_card/_preview.html.erb
  app/views/sage/examples/objects/live_stream_video_grid/_markup.html.erb
  app/views/sage/examples/objects/live_stream_video_grid/_preview.html.erb
Labels: Review

#172 Update fonts with cleaner artifacts
  app/assets/fonts/sage/Sage.eot
  app/assets/fonts/sage/Sage.ttf
  app/assets/fonts/sage/Sage.woff
  app/assets/fonts/sage/Sage.woff2
Labels: Review

#169 Grid alignment classes
  app/assets/stylesheets/sage/docs/_grid.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/layout/_grid.scss
  app/views/sage/pages/grid.html.erb
Labels: Review, enhancement, thumbsup

#168 Grid documentation details
  app/assets/stylesheets/sage/docs/_code.scss
  app/assets/stylesheets/sage/docs/_grid.scss
  app/assets/stylesheets/sage/docs/_quick_links.scss
  app/assets/stylesheets/sage/docs/_text.scss
  app/assets/stylesheets/sage/sage_docs.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/layout/_grid.scss
  app/views/sage/pages/grid.html.erb
Labels: Review, documentation, thumbsup

#173 Avatar Updates
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/assets/stylesheets/sage/system/vendor/_reboot.scss
  app/views/sage/examples/objects/live_avatar/_markup.html.erb
  app/views/sage/examples/objects/live_avatar/_preview.html.erb
  app/views/sage/examples/objects/live_avatar/_props.html.erb
Labels: Review

#175 Jcm pagination
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/objects/_pagination.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/pagination/_preview.html.erb
  app/views/sage/examples/objects/pagination/_props.html.erb
  app/views/sage/examples/objects/pagination/_rules_do.html.erb
  app/views/sage/examples/objects/pagination/_rules_dont.html.erb
Labels: Review

#183 minor style ttweaks
  app/assets/stylesheets/sage/system/patterns/objects/_pagination.scss
Labels: Review

#176 System banner/alert styles
  app/assets/javascripts/sage/docs/banner.js
  app/assets/javascripts/sage/sage_docs.js
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/banner.js
  app/assets/javascripts/sage/system/example.js
  app/assets/javascripts/sage/system/init.js
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/layout/_page.scss
  app/assets/stylesheets/sage/system/patterns/objects/_alert.scss
  app/assets/stylesheets/sage/system/patterns/objects/_banner.scss
  app/assets/stylesheets/sage/system/patterns/objects/_pagination.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/examples/objects/alert/_preview.html.erb
  app/views/sage/examples/objects/alert/_props.html.erb
  app/views/sage/examples/objects/alert/_rules_do.html.erb
  app/views/sage/examples/objects/alert/_rules_dont.html.erb
  app/views/sage/examples/objects/banner/_markup.html.erb
  app/views/sage/examples/objects/banner/_preview.html.erb
  app/views/sage/examples/objects/banner/_props.html.erb
  app/views/sage/examples/objects/banner/_rules_dont.html.erb
  app/views/sage/examples/objects/form_section/_preview.html.erb
Labels: Review, thumbsup

#181 Simpleform Compatibility - Pt 1
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/views/sage/examples/elements/form_input/_preview.html.erb
  app/views/sage/examples/elements/switch/_preview.html.erb
Labels: Review

#189 Remove default `sage-btn` margins
  app/assets/stylesheets/sage/docs/_button.scss
  app/assets/stylesheets/sage/sage_docs.css.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/objects/_banner.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/button/_markup.html.erb
  app/views/sage/examples/elements/button/_preview.html.erb
  app/views/sage/examples/elements/button/_props.html.erb
  app/views/sage/examples/objects/banner/_markup.html.erb
Labels: Review

#192 Convert tooltip markup to .erb
  app/views/sage/examples/elements/tooltip/_markup.html.erb
  app/views/sage/examples/elements/tooltip/_preview.html.erb
Labels: Review

#193 Convert checkbox markup to .erb
  app/views/sage/examples/elements/checkbox/_markup.html.erb
  app/views/sage/examples/elements/checkbox/_preview.html.erb
Labels: Review

#179 Revise alert styling and documentation
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/alert.js
  app/assets/javascripts/sage/system/init.js
  app/assets/stylesheets/sage/system/patterns/objects/_alert.scss
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/objects/alert/_markup.html.erb
  app/views/sage/examples/objects/alert/_preview.html.erb
Labels: Review

#194 Bump version to 0.12.0
  lib/sage/version.rb
Labels: Review

#195 Jcm sage 12.1
  app/helpers/sage/application_helper.rb
  app/views/sage/application/_assistant.html.erb
  lib/sage/version.rb
Labels: Review

#196 Convert radio markup to .erb
  app/views/sage/examples/elements/radio/_markup.html.erb
  app/views/sage/examples/elements/radio/_preview.html.erb
Labels: Review

#199 Convert label markup to .erb
  app/views/sage/examples/elements/label/_markup.html.erb
  app/views/sage/examples/elements/label/_preview.html.erb
Labels: Review

#197 Convert switch markup to .erb
  app/views/sage/examples/elements/switch/_markup.html.erb
  app/views/sage/examples/elements/switch/_preview.html.erb
Labels: Review

#188 Jcm panel updates
  app/assets/stylesheets/sage/docs/_theme.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/objects/_panel.scss
  app/views/sage/examples/objects/panel/_preview.html.erb
Labels: Review

#204 Convert form input markup to .erb
  app/views/sage/examples/elements/form_input/_markup.html.erb
  app/views/sage/examples/elements/form_input/_preview.html.erb
Labels: Review

#205 Convert form textarea markup to .erb
  app/views/sage/examples/elements/form_input/_markup.html.erb
  app/views/sage/examples/elements/form_textarea/_markup.html.erb
  app/views/sage/examples/elements/form_textarea/_preview.html.erb
Labels: Review

#206 Convert loader markup to .erb
  app/views/sage/examples/elements/loader/_markup.html.erb
  app/views/sage/examples/elements/loader/_preview.html.erb
Labels: Review

#200 Sage-Select
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_select.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/form_select/_preview.html.erb
  app/views/sage/examples/elements/form_select/_props.html.erb
  app/views/sage/examples/elements/form_select/_rules_do.html.erb
  app/views/sage/examples/elements/form_select/_rules_dont.html.erb
Labels: Review

#207 Convert danger button markup to .erb
  app/views/sage/examples/elements/danger_button/_markup.html.erb
  app/views/sage/examples/elements/danger_button/_preview.html.erb
Labels: Review

#212 JS error on products/superadmin
  app/assets/javascripts/sage/system/banner.js
  app/assets/javascripts/sage/system/init.js
  app/views/sage/application/_scripts.html.erb
Labels: bug

#214 Sage panel overflow hides content on mobile devices
  app/assets/stylesheets/sage/system/patterns/objects/_panel.scss
Labels: Review, bug

#211 Convert table markup to .erb
  app/views/sage/examples/elements/table/_markup.html.erb
  app/views/sage/examples/elements/table/_preview.html.erb
Labels: Review

#210 Convert live stream wrapper markup to .erb
  app/views/sage/examples/elements/live_stream_wrapper/_markup.html.erb
  app/views/sage/examples/elements/live_stream_wrapper/_preview.html.erb
Labels: Review
