Repository Kajabi/sage, pull requests merged in 2020-06, with the labels that each got.

#270 Bump to 0.16.0
  lib/sage/version.rb
Labels: Review

#281 Sage Webpack: Update Stylelint Implementation
  config/webpack/development.js
  package.json
  postcss.config.js
  yarn.lock
Labels: Review, webpacker

#284 Small edits in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Review

#285 Remove default line height [0.17.2]
  README.md
  lib/sage-frontend/stylesheets/system/vendor/_reboot.scss
Labels: Review, bug :space_invader:, documentation

#286 Version 1.0
  package.json
Labels: Review

#289 Sage docs sidebar nav modifications
  app/views/application/_sidebar.html.erb
  lib/sage-frontend/stylesheets/system/patterns/objects/_nav.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sidebar.scss
  lib/sage-frontend/stylesheets/system/tokens/_sidebar.scss
Labels: Review, documentation

#298 Checkbox documentation updates
  app/helpers/elements_helper.rb
  app/views/examples/elements/checkbox/_props.html.erb
Labels: Review

#299 Radio documentation updates
  app/helpers/elements_helper.rb
Labels: Review

#300 Label documentation updates
  app/views/examples/elements/label/_props.html.erb
Labels: documentation, thumbsup

#302 Billboard documentation updates
  app/helpers/objects_helper.rb
Labels: documentation, thumbsup

#303 Tabs documentation updates
  app/helpers/objects_helper.rb
  app/views/examples/objects/tabs/_props.html.erb
Labels: Review, documentation

#304 Pagination documentation updates
  app/helpers/objects_helper.rb
  app/views/examples/objects/pagination/_props.html.erb
  app/views/examples/objects/pagination/_rules_do.html.erb
  app/views/examples/objects/pagination/_rules_dont.html.erb
Labels: Review, documentation

#305 Panel documentation updates
  app/helpers/objects_helper.rb
Labels: Review, documentation

#306 Nav documentation updates
  app/helpers/objects_helper.rb
  app/views/examples/objects/nav/_props.html.erb
Labels: Review, documentation

#310 [BUG] Input group button margin
  lib/sage-frontend/stylesheets/docs/_button.scss
Labels: Review, bug :space_invader:

#309 Reduce `line-height` in Alert title
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
Labels: Review, enhancement

#308 [BUG] Banner text out of alignment
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_banner.scss
Labels: Review, bug :space_invader:

#276 Adjust z-index scale
  lib/sage-frontend/stylesheets/docs/_example.scss
  lib/sage-frontend/stylesheets/system/tokens/_z_index.scss
Labels: Review, kajabi

#307 Typography updates
  app/views/pages/typography.html.erb
  lib/sage-frontend/stylesheets/docs/_specs.scss
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/tokens/_font_size.scss
  lib/sage-frontend/stylesheets/system/tokens/_font_weight.scss
  lib/sage-frontend/stylesheets/system/tokens/_letter_spacing.scss
  lib/sage-frontend/stylesheets/system/tokens/_line_height.scss
Labels: documentation, thumbsup

#311 Page heading documentation updates
  app/helpers/objects_helper.rb
Labels: Review, documentation

#312 Form section documentation updates
  app/helpers/objects_helper.rb
Labels: Review, documentation

#291 adding voice and tone guides
  app/views/application/_sidebar.html.erb
  app/views/pages/index.html.erb
Labels: Review

#313 Form select documentation updates
  app/helpers/elements_helper.rb
  app/views/examples/elements/form_select/_props.html.erb
  app/views/examples/elements/form_select/_rules_do.html.erb
  app/views/examples/elements/form_select/_rules_dont.html.erb
Labels: Review, documentation
