Repository Kajabi/sage, pull requests merged in 2020-07, with the labels that each got.

#314 Description documentation updates
  app/helpers/elements_helper.rb
Labels: Review, documentation

#315 Deprecate link button
  app/helpers/elements_helper.rb
  app/views/examples/elements/link_button/_markup.html.erb
  app/views/examples/elements/link_button/_preview.html.erb
  app/views/examples/elements/link_button/_props.html.erb
  app/views/examples/elements/link_button/_rules_do.html.erb
  app/views/examples/elements/link_button/_rules_dont.html.erb
Labels: Review, documentation

#318 Restructure nav markup to use nested list for sub links.
  app/views/examples/objects/nav/_markup.html.erb
  app/views/examples/objects/nav/_preview.html.erb
Labels: Review

#319 Consolidate monospace fonts and Stylelint cleanup
  lib/sage-frontend/stylesheets/docs/_token.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
  lib/sage-frontend/stylesheets/system/vendor/_reboot.scss
Labels: Review

#321 Optimize documentation related images
  lib/sage-frontend/images/docs/card/card-placeholder-lg.png
  lib/sage-frontend/images/docs/card/card-placeholder-sm.png
  lib/sage-frontend/images/docs/sage_illustration.png
  lib/sage-frontend/images/docs/sage_structure.png
Labels: Review, documentation

#325 Code status updates
  app/helpers/elements_helper.rb
  app/helpers/objects_helper.rb
  app/views/application/_status_item.html.erb
  app/views/pages/status.html.erb
  lib/sage-frontend/stylesheets/docs/_status_table.scss
Labels: Review, a11y

#324 Add input prefix and suffix
  app/views/application/_scripts.html.erb
  app/views/examples/elements/form_input/_markup.html.erb
  app/views/examples/elements/form_input/_preview.html.erb
  app/views/examples/elements/meter/_preview.html.erb
  app/views/examples/objects/input_group/_markup.html.erb
  lib/sage-frontend/javascript/system/index.js
  lib/sage-frontend/javascript/system/init.js
  lib/sage-frontend/javascript/system/inputaffixes.js
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
Labels: Review, javascript

#326 Pagination Adjustments
  app/views/examples/objects/pagination/_markup.html.erb
  app/views/examples/objects/pagination/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/objects/_pagination.scss
Labels: Review

#327 Add tiny button
  app/views/examples/elements/button/_markup.html.erb
  app/views/examples/elements/button/_preview.html.erb
  app/views/examples/elements/button/_rules_dont.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
Labels: Review

#328 Add sandbox and lint
  app/controllers/pages_controller.rb
  app/views/pages/sandbox.html.erb
  config/routes.rb
  lib/sage-frontend/stylesheets/docs/_docs_container.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_form_section.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_pagination.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sortable.scss
Labels: Review

#267 Revisions to input hint meter and label
  app/views/examples/elements/meter/_markup.html.erb
  app/views/examples/elements/meter/_preview.html.erb
  app/views/examples/objects/input_helper/_markup.html.erb
  lib/sage-frontend/javascript/system/inputhelper.js
  lib/sage-frontend/javascript/system/meter.js
  lib/sage-frontend/stylesheets/system/patterns/elements/_meter.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_input_helper.scss
Labels: enhancement

#332 Man 278 pjs card footer indicators
  app/helpers/elements_helper.rb
  app/views/examples/elements/indicator/_markup.html.erb
  app/views/examples/elements/indicator/_preview.html.erb
  app/views/examples/elements/indicator/_props.html.erb
  app/views/examples/elements/indicator/_rules_do.html.erb
  app/views/examples/elements/indicator/_rules_dont.html.erb
  app/views/examples/objects/card/_preview.html.erb
  app/views/examples/objects/pagination/_markup.html.erb
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_indicator.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
Labels: Review, enhancement

#334 v1.3.0
  package.json
Labels: Review

#329 Sidenav style updates
  lib/sage-frontend/stylesheets/system/layout/_content.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_nav.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sidebar.scss
Labels: Review, enhancement

#337 Hotfix: Update Sage Form Section padding
  lib/sage-frontend/stylesheets/system/patterns/objects/_form_section.scss
Labels: Review, bug :space_invader:

#338 Sage Docs: Rails Routing & Navigation Bars
  app/controllers/pages_controller.rb
  app/helpers/application_helper.rb
  app/views/application/_sidebar.html.erb
  app/views/application/_sidebar_elements.html.erb
  app/views/application/_sidebar_objects.html.erb
  app/views/application/_sidebar_styles.html.erb
  app/views/examples/elements/_element.html.erb
  app/views/examples/elements/_element_preview.html.erb
  app/views/examples/objects/_object.html.erb
  app/views/examples/objects/_object_preview.html.erb
  app/views/examples/shared/_heading.html.erb
  app/views/examples/shared/_quick_links.html.erb
  app/views/pages/color.html.erb
  app/views/pages/container.html.erb
  app/views/pages/elements.html.erb
  app/views/pages/grid.html.erb
  app/views/pages/objects.html.erb
  app/views/pages/status.html.erb
  app/views/pages/token.html.erb
  app/views/pages/typography.html.erb
  app/views/pages/utilities.html.erb
  config/routes.rb
  lib/sage-frontend/stylesheets/docs/_quick_links.scss
  lib/sage-frontend/stylesheets/docs/_sidebar.scss
  lib/sage-frontend/stylesheets/docs/_theme.scss
Labels: Review

#340 New icon font system
  app/views/pages/icon.html.erb
  lib/sage-frontend/fonts/sage/Sage.eot
  lib/sage-frontend/fonts/sage/Sage.svg
  lib/sage-frontend/fonts/sage/Sage.ttf
  lib/sage-frontend/fonts/sage/Sage.woff
  lib/sage-frontend/fonts/sage/Sage.woff2
  lib/sage-frontend/stylesheets/docs/_icon.scss
  lib/sage-frontend/stylesheets/system/core/_icons.scss
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/tokens/_icon.scss
Labels: Icon, enhancement

#339 Update README.md
  README.md
Labels: DO NOT MERGE :stop_sign:, Review, documentation

#330 Update Type Specs
  app/helpers/tokens_helper.rb
  app/views/examples/elements/button/_preview.html.erb
  app/views/examples/objects/sortable/_markup.html.erb
  app/views/pages/typography.html.erb
  lib/sage-frontend/stylesheets/docs/_token.scss
  lib/sage-frontend/stylesheets/system/core/_functions.scss
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_meter.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_switch.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_table.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_banner.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage-frontend/stylesheets/system/tokens/_font_size.scss
  lib/sage-frontend/stylesheets/system/tokens/_line_height.scss
  lib/sage-frontend/stylesheets/system/vendor/_reboot.scss
Labels: Review, thumbsup

#331 Kajabi Admin Site Navigation: New JS Init Strategy, Sage Tabs, & Updates
  app/views/examples/objects/modal/_markup.html.erb
  app/views/examples/objects/modal/_preview.html.erb
  app/views/examples/objects/panel/_markup.html.erb
  app/views/examples/objects/tabs/_markup.html.erb
  app/views/examples/objects/tabs/_preview.html.erb
  lib/sage-frontend/javascript/system/dropdown.js
  lib/sage-frontend/javascript/system/index.js
  lib/sage-frontend/javascript/system/init.js
  lib/sage-frontend/javascript/system/modal.js
  lib/sage-frontend/javascript/system/sortable.js
  lib/sage-frontend/javascript/system/tabs.js
  lib/sage-frontend/javascript/system/tooltip.js
  lib/sage-frontend/javascript/system/util.js
  lib/sage-frontend/stylesheets/system/patterns/elements/_loader.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage-frontend/stylesheets/system/tokens/_container.scss
  lib/sage-frontend/stylesheets/system/vendor/_reboot.scss
  package.json
  yarn.lock
Labels: kajabi, thumbsup

#348 Patches for custom domain
  app/helpers/elements_helper.rb
  app/views/examples/elements/_element.html.erb
  app/views/examples/elements/_element_preview.html.erb
  app/views/examples/elements/button/_preview.html.erb
  app/views/examples/elements/label/_preview.html.erb
  app/views/examples/elements/link/_markup.html.erb
  app/views/examples/elements/link/_preview.html.erb
  app/views/examples/elements/link/_props.html.erb
  app/views/examples/elements/link/_rules_do.html.erb
  app/views/examples/elements/link/_rules_dont.html.erb
  app/views/examples/objects/_object.html.erb
  app/views/examples/objects/_object_preview.html.erb
  app/views/examples/objects/alert/_markup.html.erb
  app/views/examples/objects/assistant/_preview.html.erb
  app/views/examples/objects/banner/_preview.html.erb
  app/views/examples/objects/billboard/_preview.html.erb
  app/views/pages/color.html.erb
  app/views/pages/grid.html.erb
  app/views/pages/typography.html.erb
  lib/sage-frontend/stylesheets/docs/_docs_container.scss
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_link.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_banner.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_nav.scss
Labels: Review, documentation, enhancement, priority

#349 Copy button
  app/views/pages/sandbox.html.erb
  lib/sage-frontend/javascript/system/copy-button.js
  lib/sage-frontend/javascript/system/index.js
  lib/sage-frontend/javascript/system/init.js
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
Labels: Review, javascript, priority

#351 Sage Build Navbars Polish
  app/views/examples/objects/card/_markup.html.erb
  app/views/examples/objects/card/_preview.html.erb
  lib/sage-frontend/javascript/system/tabs.js
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
Labels: Review

#352 Tabs: Bottom Spacing To Pane
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
Labels: Review

#356 Adjust link element external icon spacing
  lib/sage-frontend/stylesheets/system/patterns/elements/_link.scss
Labels: Review

#357 Status Icon
  app/helpers/elements_helper.rb
  app/views/examples/elements/status_icon/_markup.html.erb
  app/views/examples/elements/status_icon/_preview.html.erb
  app/views/examples/elements/status_icon/_props.html.erb
  app/views/examples/elements/status_icon/_rules_do.html.erb
  app/views/examples/elements/status_icon/_rules_dont.html.erb
  app/views/examples/objects/modal/_markup.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_status_icon.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tooltip.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sortable.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
Labels: Review, enhancement

#359 Fix tabs click handler bug
  lib/sage-frontend/javascript/system/tabs.js
Labels: Review, bug :space_invader:

#355 Panelize Sage Docs
  app/views/examples/elements/_element.html.erb
  app/views/examples/elements/_element_preview.html.erb
  app/views/examples/objects/_object.html.erb
  app/views/examples/objects/_object_preview.html.erb
  app/views/examples/shared/_code.html.erb
  app/views/examples/shared/_preview.html.erb
  app/views/examples/shared/_props.html.erb
  app/views/examples/shared/_rules.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/breakout.html.erb
  app/views/pages/color.html.erb
  app/views/pages/index.html.erb
  app/views/pages/token.html.erb
  app/views/pages/typography.html.erb
  lib/sage-frontend/stylesheets/docs/_example.scss
  lib/sage-frontend/stylesheets/docs/_icon.scss
  lib/sage-frontend/stylesheets/docs/_quick_links.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
Labels: Review, documentation

#360 Form Inputs Focus
  app/views/examples/objects/card/_markup.html.erb
  app/views/examples/objects/card/_preview.html.erb
  lib/sage-frontend/javascript/system/modal.js
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_textarea.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
Labels: Review
