Repository Kajabi/sage, pull requests merged in 2020-10, with the labels that each got.

#431 Add button group and revise to use rails component
  app/helpers/elements_helper.rb
  app/views/examples/elements/button/_markup.html.erb
  app/views/examples/elements/button/_preview.html.erb
  app/views/examples/elements/form_select/_rules_do.html.erb
  app/views/examples/objects/upload_card/_markup.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage_rails/app/sage_components/sage_button_group.rb
  lib/sage_rails/app/views/sage_components/_sage_button.html.erb
  lib/sage_rails/app/views/sage_components/_sage_button_group.html.erb
Labels: Review, enhancement, sage rails

#433 Alert adjustments to make closing optional
  app/helpers/objects_helper.rb
  app/views/examples/objects/alert/_markup.html.erb
  app/views/examples/objects/alert/_preview.html.erb
  app/views/examples/objects/form_section/_markup.html.erb
  lib/sage_rails/app/sage_components/sage_alert.rb
  lib/sage_rails/app/views/sage_components/_sage_alert.html.erb
Labels: Review, enhancement

#434 Color palette and placeholder text color updates
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_textarea.scss
  lib/sage-frontend/stylesheets/system/tokens/_color_palette.scss
Labels: enhancement

#436 Choices and Tabs Updates
  app/helpers/elements_helper.rb
  app/views/examples/elements/choice/_markup.html.erb
  app/views/examples/elements/choice/_preview.html.erb
  app/views/examples/elements/choice/_props.html.erb
  app/views/examples/elements/tab/_preview.html.erb
  app/views/examples/elements/tab/_props.html.erb
  app/views/examples/objects/tabs/_preview.html.erb
  app/views/examples/objects/tabs/_props.html.erb
  lib/sage-frontend/javascript/system/init.js
  lib/sage-frontend/javascript/system/tabs.js
  lib/sage-frontend/stylesheets/system/core/_icons.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage_rails/app/sage_components/sage_choice.rb
  lib/sage_rails/app/sage_components/sage_tabs.rb
  lib/sage_rails/app/sage_components/sage_tabs_pane.rb
  lib/sage_rails/app/views/sage_components/_sage_choice.html.erb
  lib/sage_rails/app/views/sage_components/_sage_tabs.html.erb
  lib/sage_rails/app/views/sage_components/_sage_tabs_pane.html.erb
Labels: Review, enhancement

#437 Add copy button, text, and card
  app/helpers/elements_helper.rb
  app/views/examples/elements/copy_text/_preview.html.erb
  app/views/examples/elements/copy_text/_props.html.erb
  app/views/examples/elements/copy_text/_rules_do.html.erb
  app/views/examples/elements/copy_text/_rules_dont.html.erb
  lib/sage-frontend/javascript/system/copy-button.js
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_copy_text.scss
  lib/sage_rails/app/sage_components/sage_copy_button.rb
  lib/sage_rails/app/sage_components/sage_copy_text.rb
  lib/sage_rails/app/sage_components/sage_copy_text_card.rb
  lib/sage_rails/app/views/sage_components/_sage_copy_button.html.erb
  lib/sage_rails/app/views/sage_components/_sage_copy_text.html.erb
  lib/sage_rails/app/views/sage_components/_sage_copy_text_card.html.erb
Labels: Review, enhancement

#438 Update README.md
  README.md
Labels: bug :space_invader:

#443 Update tabs js prop
  lib/sage_rails/app/views/sage_components/_sage_tabs.html.erb
Labels: bug :space_invader:

#444 Patch tab loading bug
  lib/sage_rails/app/views/sage_components/_sage_tabs.html.erb
Labels: bug :space_invader:

#445 Table updates
  app/helpers/elements_helper.rb
  app/views/examples/elements/table/_preview.html.erb
  app/views/pages/sandbox.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_table.scss
  lib/sage_rails/app/sage_components/sage_table.rb
  lib/sage_rails/app/views/sage_components/_sage_table.html.erb
Labels: enhancement

#446 Misc adjustments Post 1.15.0
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/layout/_grid.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_table.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/tokens/_color_palette.scss
  lib/sage_rails/app/views/sage_components/_sage_breadcrumbs.html.erb
Labels: bug :space_invader:, enhancement

#450 Alert Updates
  app/views/examples/objects/alert/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
  lib/sage_rails/app/sage_components/sage_alert.rb
  lib/sage_rails/app/views/sage_components/_sage_alert.html.erb
Labels: Review

#451 A few more misc patches post 1.15
  app/views/pages/sandbox.html.erb
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/layout/_grid-templates.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_property.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage_rails/app/sage_components/sage_card.rb
  lib/sage_rails/app/sage_components/sage_panel.rb
  lib/sage_rails/app/views/sage_components/_sage_card.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel.html.erb
  lib/sage_rails/app/views/sage_components/_sage_property.html.erb
Labels: enhancement

#439 Update SageRails SagePagination component
  lib/sage_rails/app/sage_components/sage_pagination.rb
  lib/sage_rails/app/views/sage_components/_sage_pagination.html.erb
Labels: sage rails

#448 Align Avatars to Spec
  app/helpers/objects_helper.rb
  app/views/examples/objects/avatar/_markup.html.erb
  app/views/examples/objects/avatar/_preview.html.erb
  app/views/examples/objects/avatar/_props.html.erb
  app/views/examples/objects/avatar/_rules_do.html.erb
  app/views/examples/objects/avatar/_rules_dont.html.erb
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_avatar.scss
  lib/sage_rails/app/sage_components/sage_avatar.rb
  lib/sage_rails/app/views/sage_components/_sage_avatar.html.erb
Labels: UXD :grey_exclamation:

#455 Alert Follow Up
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
  lib/sage_rails/app/views/sage_components/_sage_alert.html.erb
Labels: Review, bug :space_invader:

#461 Sage Checkbox - align to spec
  app/helpers/elements_helper.rb
  app/helpers/tokens_helper.rb
  app/views/examples/elements/checkbox/_markup.html.erb
  app/views/examples/elements/checkbox/_preview.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_checkbox.scss
  lib/sage-frontend/stylesheets/system/tokens/_border.scss
  lib/sage_rails/app/sage_components/sage_checkbox.rb
  lib/sage_rails/app/views/sage_components/_sage_checkbox.html.erb
Labels: RAILS :exclamation:, UXD :grey_exclamation:

#463 Patches issue with checkbox being squished
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
Labels: bug :space_invader:

#477 [Rails] Fix Broken :html_attributes Concatenation
  lib/sage_rails/app/sage_components/sage_component.rb
  lib/sage_rails/app/sage_components/sage_pagination.rb
  lib/sage_rails/app/views/sage_components/_sage_card.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_block.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_figure.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_footer.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_header.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_list.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_list_item.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_row.html.erb
  lib/sage_rails/app/views/sage_components/_sage_card_stack.html.erb
  lib/sage_rails/app/views/sage_components/_sage_empty_state.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_block.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_figure.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_footer.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_header.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_list.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_list_item.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_row.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_stack.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_subheader.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_tile.html.erb
  lib/sage_rails/app/views/sage_components/_sage_panel_tiles.html.erb
  lib/sage_rails/app/views/sage_components/_sage_property.html.erb
Labels: RAILS :heavy_check_mark:

#462 Align Radio to spec and add Sage Rails component
  app/helpers/elements_helper.rb
  app/views/examples/elements/radio/_markup.html.erb
  app/views/examples/elements/radio/_preview.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_radio.scss
  lib/sage_rails/app/sage_components/sage_radio.rb
  lib/sage_rails/app/views/sage_components/_sage_radio.html.erb
Labels: RAILS :exclamation:

#476 Add Sage Rails Switch and align to spec
  app/helpers/elements_helper.rb
  app/views/examples/elements/switch/_markup.html.erb
  app/views/examples/elements/switch/_preview.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_switch.scss
  lib/sage_rails/app/sage_components/sage_switch.rb
  lib/sage_rails/app/views/sage_components/_sage_switch.html.erb
Labels: RAILS :exclamation:

#478 Update warning alert icon color
  lib/sage-frontend/stylesheets/system/patterns/objects/_alert.scss
Labels: bug :space_invader:

#481 Tooltips: allow children to rollover
  lib/sage-frontend/javascript/system/tooltip.js
Labels: bug :space_invader:

#504 Adjust form input message (hint text) spacing
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
Labels: bug :space_invader:
