Repository Kajabi/sage, pull requests merged in 2020-09, with the labels that each got.

#403 Misc tidying for version bump
  app/views/examples/objects/panel/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
Labels: bug :space_invader:

#402 Updated dropdown menu
  app/views/examples/elements/button/_markup.html.erb
  app/views/examples/elements/form_select/_markup.html.erb
  app/views/examples/elements/form_select/_preview.html.erb
  app/views/examples/objects/dropdown/_markup.html.erb
  app/views/examples/objects/dropdown/_preview.html.erb
  lib/sage-frontend/javascript/system/dropdown.js
  lib/sage-frontend/javascript/system/init.js
  lib/sage-frontend/javascript/system/select.js
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
Labels: bug :space_invader:, enhancement

#410 Add icons to labels
  app/views/examples/elements/label/_markup.html.erb
  app/views/examples/elements/label/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
Labels: enhancement

#411 Update icons
  app/views/pages/icon.html.erb
  lib/sage-frontend/fonts/sage/Sage.eot
  lib/sage-frontend/fonts/sage/Sage.svg
  lib/sage-frontend/fonts/sage/Sage.ttf
  lib/sage-frontend/fonts/sage/Sage.woff
  lib/sage-frontend/stylesheets/system/tokens/_icon.scss
Labels: enhancement

#412 Dropdown adjustments
  app/views/examples/objects/dropdown/_preview.html.erb
  lib/sage-frontend/javascript/system/dropdown.js
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
Labels: enhancement

#414 Products Navbars Bugfixes
  bin/sage-local-link-frontend-only.sh
  lib/sage-frontend/javascript/system/modal.js
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
Labels: bug :space_invader:, kajabi, priority

#417 New panels and cards structure, Part 2
  app/controllers/pages_controller.rb
  app/helpers/application_helper.rb
  app/views/application/_assistant.html.erb
  app/views/application/_sidebar.html.erb
  app/views/application/_sidebar_elements.html.erb
  app/views/application/_sidebar_objects.html.erb
  app/views/application/_sidebar_styles.html.erb
  app/views/examples/elements/_element_preview.html.erb
  app/views/examples/elements/button/_props.html.erb
  app/views/examples/elements/icon_card/_markup.html.erb
  app/views/examples/elements/table/_preview.html.erb
  app/views/examples/objects/_object_preview.html.erb
  app/views/examples/objects/expandable_card/_preview.html.erb
  app/views/examples/objects/input_group/_props.html.erb
  app/views/examples/shared/_code.html.erb
  app/views/examples/shared/_preview.html.erb
  app/views/examples/shared/_props.html.erb
  app/views/examples/shared/_rules.html.erb
  app/views/pages/color.html.erb
  app/views/pages/container.html.erb
  app/views/pages/element.html.erb
  app/views/pages/elements.html.erb
  app/views/pages/grid.html.erb
  app/views/pages/icon.html.erb
  app/views/pages/index.html.erb
  app/views/pages/object.html.erb
  app/views/pages/objects.html.erb
  app/views/pages/panels_cards.html.erb
  app/views/pages/token.html.erb
  app/views/pages/typography.html.erb
  app/views/pages/utilities.html.erb
  config/routes.rb
  lib/generators/sage_page/templates/page.html.erb
  lib/sage-frontend/stylesheets/docs/_code.scss
  lib/sage-frontend/stylesheets/docs/_example.scss
  lib/sage-frontend/stylesheets/system/core/_functions.scss
  lib/sage-frontend/stylesheets/system/core/_icons.scss
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_link.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_menu_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_search.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_status_icon.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_avatar.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_data_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_expandable_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_input_group.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sortable.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_upload_card.scss
Labels: enhancement

#416 SageCatalogCard (+ SageRails Docs support)
  app/helpers/elements_helper.rb
  app/helpers/objects_helper.rb
  app/views/examples/elements/_element.html.erb
  app/views/examples/elements/button/_preview.html.erb
  app/views/examples/objects/_object.html.erb
  app/views/examples/objects/catalog_card/_preview.html.erb
  app/views/examples/objects/catalog_card/_props.html.erb
  app/views/examples/objects/catalog_card/_rules_do.html.erb
  app/views/examples/objects/catalog_card/_rules_dont.html.erb
  app/views/examples/shared/_code.html.erb
  app/views/examples/shared/_legacy_code.html.erb
  lib/sage-frontend/javascript/docs/example.js
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
  lib/sage-frontend/stylesheets/system/tokens/_border.scss
  lib/sage_rails/app/sage_components/sage_catalog_card.rb
  lib/sage_rails/app/views/sage_components/_sage_catalog_card.html.erb
Labels: Review

#419 Refactor Button outline -> mixin and SageLabel--interactive
  app/views/examples/elements/label/_preview.html.erb
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
Labels: Review

#420 SageLabel Rails, update Docs preview for SageDropdown, minor adjustments
  app/helpers/elements_helper.rb
  app/helpers/objects_helper.rb
  app/views/examples/elements/label/_markup.html.erb
  app/views/examples/elements/label/_preview.html.erb
  app/views/examples/objects/catalog_item/_preview.html.erb
  app/views/examples/objects/catalog_item/_props.html.erb
  app/views/examples/objects/catalog_item/_rules_do.html.erb
  app/views/examples/objects/catalog_item/_rules_dont.html.erb
  app/views/examples/objects/dropdown/_markup.html.erb
  app/views/examples/objects/dropdown/_preview.html.erb
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_item.scss
  lib/sage_rails/app/sage_components/sage_catalog_item.rb
  lib/sage_rails/app/sage_components/sage_dropdown.rb
  lib/sage_rails/app/sage_components/sage_label.rb
  lib/sage_rails/app/views/sage_components/_sage_button.html.erb
  lib/sage_rails/app/views/sage_components/_sage_catalog_item.html.erb
  lib/sage_rails/app/views/sage_components/_sage_dropdown.html.erb
  lib/sage_rails/app/views/sage_components/_sage_label.html.erb
Labels: Review

#413 Update page heading to include additional items
  app/helpers/objects_helper.rb
  app/views/examples/elements/breadcrumbs/_markup.html.erb
  app/views/examples/objects/page_heading/_markup.html.erb
  app/views/examples/objects/page_heading/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
  lib/sage_rails/app/sage_components/sage_page_heading.rb
  lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
Labels: Review, enhancement

#425 Sage v1.12.0 Followup
  lib/sage-frontend/javascript/system/modal.js
  lib/sage-frontend/stylesheets/system/patterns/objects/_sortable.scss
  lib/sage_rails/app/sage_components/sage_empty_state.rb
  lib/sage_rails/app/views/sage_components/_sage_empty_state.html.erb
Labels: Review

#424 SageOutline Item
  app/helpers/objects_helper.rb
  app/views/examples/objects/outline_item/_preview.html.erb
  app/views/examples/objects/outline_item/_props.html.erb
  app/views/examples/objects/outline_item/_rules_do.html.erb
  app/views/examples/objects/outline_item/_rules_dont.html.erb
  app/views/pages/sandbox.html.erb
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_outline_item.scss
  lib/sage_rails/app/sage_components/sage_outline_item.rb
  lib/sage_rails/app/views/sage_components/_sage_outline_item.html.erb
Labels: Review

#426 SageSortable: Refactor, add "Card" and (implicit) "List" types
  app/helpers/objects_helper.rb
  app/views/examples/objects/sortable/_markup.html.erb
  app/views/examples/objects/sortable/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_status_icon.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_sortable.scss
  lib/sage_rails/app/sage_components/sage_sortable.rb
  lib/sage_rails/app/sage_components/sage_sortable_item.rb
  lib/sage_rails/app/views/sage_components/_sage_sortable_item.html.erb
Labels: Review

#427 Tooltip Sizing Adjustment
  lib/sage-frontend/stylesheets/system/patterns/elements/_tooltip.scss
Labels: bug :space_invader:

#428 Improve Data Card
  app/views/examples/objects/data_card/_markup.html.erb
  app/views/examples/objects/data_card/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/objects/_data_card.scss
Labels: Review, enhancement

#429 Revise tabs spacing settings, add divider
  app/helpers/objects_helper.rb
  app/views/examples/objects/tabs/_markup.html.erb
  app/views/examples/objects/tabs/_preview.html.erb
  app/views/examples/objects/tabs/_props.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage_rails/app/sage_components/sage_tabs.rb
  lib/sage_rails/app/views/sage_components/_sage_tabs.html.erb
Labels: Review, enhancement
