Repository Kajabi/sage, pull requests merged in 2020-03, with the labels that each got.

#54 Update quick links module
  app/assets/stylesheets/sage/utilities/_media.scss
  app/assets/stylesheets/sage_docs/_quick_links.scss
  app/views/sage/pages/accessibility.html.erb
  app/views/sage/pages/browser.html.erb
  app/views/sage/pages/color.html.erb
  app/views/sage/pages/container.html.erb
  app/views/sage/pages/conventions.html.erb
  app/views/sage/pages/elements.html.erb
  app/views/sage/pages/generators.html.erb
  app/views/sage/pages/index.html.erb
  app/views/sage/pages/language.html.erb
  app/views/sage/pages/start.html.erb
  app/views/sage/pages/token.html.erb
  app/views/sage/pages/typography.html.erb
  app/views/sage/pages/utilities.html.erb
Labels: Review

#53 Live Markup, Style, JS Reloading
  .gitignore
  Gemfile
  README.md
  app/assets/images/sage/sage_illustration.png
  app/views/sage/pages/index.html.erb
  app/views/sage/pages/start.html.erb
  package-lock.json
  package.json
Labels: Review

#67 Systemized z-index values
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/patterns/elements/_button.scss
  app/assets/stylesheets/sage/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/tokens/_z_index.scss
  app/assets/stylesheets/sage_docs.css.scss
  app/assets/stylesheets/sage_docs/_token.scss
  app/helpers/sage/tokens_helper.rb
Labels: Review

#62 layout to layout folder
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/layout/_assistant.scss
  app/assets/stylesheets/sage/layout/_banner.scss
  app/assets/stylesheets/sage/layout/_content.scss
  app/assets/stylesheets/sage/layout/_form_section.scss
  app/assets/stylesheets/sage/layout/_nav.scss
  app/assets/stylesheets/sage/layout/_page.scss
  app/assets/stylesheets/sage/layout/_panel.scss
  app/assets/stylesheets/sage/layout/_sidebar.scss
  app/assets/stylesheets/sage/layout/_stage.scss
  app/assets/stylesheets/sage/layout/_tabs.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/content/_preview.html.erb
  app/views/sage/examples/objects/page/_preview.html.erb
Labels: Review

#68 fixing include
  app/assets/stylesheets/sage/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/patterns/objects/_banner.scss
  app/assets/stylesheets/sage/patterns/objects/_form_section.scss
  app/assets/stylesheets/sage/patterns/objects/_nav.scss
  app/assets/stylesheets/sage/patterns/objects/_panel.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/patterns/objects/_tabs.scss
Labels: Review

#66 Loading indicators
  app/assets/images/svg/loader.svg
  app/assets/images/svg/spinner.svg
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/patterns/elements/_loader.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/loader/_preview.html.erb
  app/views/sage/examples/elements/loader/_props.html.erb
  app/views/sage/examples/elements/loader/_rules_do.html.erb
  app/views/sage/examples/elements/loader/_rules_dont.html.erb
Labels: Review

#69 Jcm docs
  app/controllers/sage/pages_controller.rb
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/application/_sidebar_guidelines.html.erb
  app/views/sage/pages/accessibility.html.erb
  app/views/sage/pages/browser.html.erb
  app/views/sage/pages/conventions.html.erb
  app/views/sage/pages/generators.html.erb
  app/views/sage/pages/index.html.erb
  app/views/sage/pages/language.html.erb
  app/views/sage/pages/start.html.erb
  config/routes.rb
Labels: Review

#59 Accessibility updates in documentation
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/core/_animations.scss
  app/assets/stylesheets/sage/core/_mixins.scss
  app/assets/stylesheets/sage/patterns/elements/_button.scss
  app/assets/stylesheets/sage/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/tokens/_sidebar.scss
  app/assets/stylesheets/sage/utilities/_hidden.scss
  app/views/layouts/sage/application.html.erb
  app/views/layouts/sage/breakout.html.erb
  app/views/sage/application/_assistant.html.erb
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/examples/objects/sidebar/_preview.html.erb
  config/initializers/assets.rb
  test/dummy/app/assets/javascripts/docs.js
  test/dummy/app/views/layouts/application.html.erb
  test/dummy/public/404.html
  test/dummy/public/422.html
  test/dummy/public/500.html
Labels: Review

#63 new status page
  app/assets/stylesheets/sage_docs.css.scss
  app/assets/stylesheets/sage_docs/_status_key.scss
  app/assets/stylesheets/sage_docs/_status_table.scss
  app/controllers/sage/pages_controller.rb
  app/helpers/sage/elements_helper.rb
  app/helpers/sage/objects_helper.rb
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/application/_status_item.html.erb
  app/views/sage/application/_status_key.html.erb
  app/views/sage/pages/status.html.erb
  config/routes.rb
  lib/generators/sage_element/sage_element_generator.rb
  lib/generators/sage_object/sage_object_generator.rb
Labels: Review

#71 REGRESSION: quick link structure
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/pages/color.html.erb
  app/views/sage/pages/container.html.erb
  app/views/sage/pages/elements.html.erb
  app/views/sage/pages/objects.html.erb
  app/views/sage/pages/status.html.erb
  app/views/sage/pages/token.html.erb
  app/views/sage/pages/typography.html.erb
  app/views/sage/pages/utilities.html.erb
Labels: Review, regression

#76 Stylelint repo cleanup
  .stylelintrc.json
  app/assets/stylesheets/sage/core/_mixins.scss
  app/assets/stylesheets/sage/core/_typography.scss
  app/assets/stylesheets/sage/icons/_map.scss
  app/assets/stylesheets/sage/icons/icons.scss
  app/assets/stylesheets/sage/layout/_container.scss
  app/assets/stylesheets/sage/layout/_content.scss
  app/assets/stylesheets/sage/layout/_grid.scss
  app/assets/stylesheets/sage/layout/_page.scss
  app/assets/stylesheets/sage/patterns/elements/_button.scss
  app/assets/stylesheets/sage/patterns/elements/_checkbox.scss
  app/assets/stylesheets/sage/patterns/elements/_icon_button.scss
  app/assets/stylesheets/sage/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/patterns/objects/_banner.scss
  app/assets/stylesheets/sage/patterns/objects/_form_section.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/patterns/objects/_tabs.scss
  app/assets/stylesheets/sage/tokens/_color_palette.scss
  app/assets/stylesheets/sage/tokens/_container.scss
  app/assets/stylesheets/sage/tokens/_font_height.scss
  app/assets/stylesheets/sage/tokens/_font_size.scss
  app/assets/stylesheets/sage/tokens/_sidebar.scss
  app/assets/stylesheets/sage/tokens/_z_index.scss
  app/assets/stylesheets/sage/vendor/_fonts.scss
  app/assets/stylesheets/sage/vendor/_reboot.scss
  app/assets/stylesheets/sage_docs.css.scss
  app/assets/stylesheets/sage_docs/_code.scss
  app/assets/stylesheets/sage_docs/_colors.scss
  app/assets/stylesheets/sage_docs/_example.scss
  app/assets/stylesheets/sage_docs/_grid.scss
  app/assets/stylesheets/sage_docs/_icon.scss
  app/assets/stylesheets/sage_docs/_quick_links.scss
  app/assets/stylesheets/sage_docs/_snippet.scss
  app/assets/stylesheets/sage_docs/_specs.scss
  app/assets/stylesheets/sage_docs/_status_key.scss
  app/assets/stylesheets/sage_docs/_status_table.scss
  app/assets/stylesheets/sage_docs/_theme.scss
  app/assets/stylesheets/sage_docs/_token.scss
  app/views/layouts/sage/application.html.erb
  lib/generators/sage_element/templates/style.scss
  lib/generators/sage_object/templates/style.scss
  lib/generators/sage_token/templates/style.scss
  lib/generators/sage_utility/templates/style.scss
  package.json
Labels: Review

#72 Refactor side nav menu
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/layout/_header.scss
  app/assets/stylesheets/sage/patterns/elements/_menu_button.scss
  app/assets/stylesheets/sage/patterns/elements/_overlay.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/tokens/_z_index.scss
  app/helpers/sage/tokens_helper.rb
  app/views/layouts/sage/application.html.erb
  app/views/layouts/sage/breakout.html.erb
  app/views/sage/application/_assistant.html.erb
  app/views/sage/examples/objects/assistant/_preview.html.erb
  app/views/sage/examples/objects/sidebar/_preview.html.erb
  test/dummy/app/assets/javascripts/docs.js
Labels: Review

#81 Update Sage version
  lib/sage/version.rb
Labels: Review

#46 SCSS variable structure - integrate CSS custom properties part 1
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/core/_animations.scss
  app/assets/stylesheets/sage/core/_fonts.scss
  app/assets/stylesheets/sage/core/_mixins.scss
  app/assets/stylesheets/sage/core/_typography.scss
  app/assets/stylesheets/sage/core/_variables.scss
  app/assets/stylesheets/sage/layout/_grid.scss
  app/assets/stylesheets/sage/patterns/elements/_button.scss
  app/assets/stylesheets/sage/patterns/elements/_checkbox.scss
  app/assets/stylesheets/sage/patterns/elements/_radio.scss
  app/assets/stylesheets/sage/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/tokens/_shadow.scss
  app/views/sage/examples/elements/radio/_preview.html.erb
Labels: Review, priority

#87 SCSS variable structure - integrate CSS custom properties part 2
  app/assets/stylesheets/sage/core/_fonts.scss
  app/assets/stylesheets/sage/core/_mixins.scss
  app/assets/stylesheets/sage/core/_typography.scss
  app/assets/stylesheets/sage/core/_variables.scss
  app/assets/stylesheets/sage/patterns/elements/_loader.scss
  app/assets/stylesheets/sage/patterns/elements/_menu_button.scss
  app/assets/stylesheets/sage/patterns/elements/_overlay.scss
  app/assets/stylesheets/sage/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/patterns/objects/_assistant.scss
  app/assets/stylesheets/sage/patterns/objects/_banner.scss
  app/assets/stylesheets/sage/patterns/objects/_form_section.scss
  app/assets/stylesheets/sage/patterns/objects/_nav.scss
  app/assets/stylesheets/sage/patterns/objects/_panel.scss
  app/assets/stylesheets/sage/patterns/objects/_sidebar.scss
  app/assets/stylesheets/sage/patterns/objects/_tabs.scss
  app/assets/stylesheets/sage_docs.css.scss
  app/assets/stylesheets/sage_docs/_code.scss
  app/assets/stylesheets/sage_docs/_colors.scss
  app/assets/stylesheets/sage_docs/_example.scss
  app/assets/stylesheets/sage_docs/_grid.scss
  app/assets/stylesheets/sage_docs/_icon.scss
  app/assets/stylesheets/sage_docs/_quick_links.scss
  app/assets/stylesheets/sage_docs/_snippet.scss
  app/assets/stylesheets/sage_docs/_specs.scss
  app/assets/stylesheets/sage_docs/_status_key.scss
  app/assets/stylesheets/sage_docs/_status_table.scss
  app/assets/stylesheets/sage_docs/_theme.scss
  app/assets/stylesheets/sage_docs/_token.scss
  app/assets/stylesheets/sage_docs/_variables.scss
Labels: Review

#90 Move JS source files
  app/assets/javascripts/sage_docs.js
  app/views/layouts/sage/application.html.erb
  test/dummy/config/initializers/assets.rb
Labels: Review

#82 Form inputs
  .stylelintrc.json
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/core/_variables.scss
  app/assets/stylesheets/sage/patterns/elements/_form_input.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/form_input/_preview.html.erb
  app/views/sage/examples/elements/form_input/_props.html.erb
  app/views/sage/examples/elements/form_input/_rules_do.html.erb
  app/views/sage/examples/elements/form_input/_rules_dont.html.erb
Labels: Review

#83 Tooltips
  app/assets/javascripts/sage.js
  app/assets/javascripts/tooltip.js
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/core/_variables.scss
  app/assets/stylesheets/sage/patterns/elements/_tooltip.scss
  app/helpers/sage/elements_helper.rb
  app/views/layouts/sage/application.html.erb
  app/views/sage/examples/elements/tooltip/_preview.html.erb
  app/views/sage/examples/elements/tooltip/_props.html.erb
  app/views/sage/examples/elements/tooltip/_rules_do.html.erb
  app/views/sage/examples/elements/tooltip/_rules_dont.html.erb
  config/initializers/assets.rb
Labels: Review

#103 Add live active mic icon
  Gemfile
  app/assets/images/svg/active-microphone.svg
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/patterns/objects/_live_active_mic.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/objects/live_active_mic/_preview.html.erb
  app/views/sage/examples/objects/live_active_mic/_props.html.erb
  app/views/sage/examples/objects/live_active_mic/_rules_do.html.erb
  app/views/sage/examples/objects/live_active_mic/_rules_dont.html.erb
Labels: Review

#106 Tooltip JS Adjustments
  app/assets/javascripts/tooltip.js
Labels: Review

#105 Code examples do not display overflow styles
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/elements/_element_preview.html.erb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/examples/objects/_object_preview.html.erb
  app/views/sage/examples/objects/form_section/_preview.html.erb
  app/views/sage/examples/utilities/_utility.html.erb
Labels: Review, thumbsup

#56 Typography style refactor
  app/assets/stylesheets/sage.css.scss
  app/assets/stylesheets/sage/core/_functions.scss
  app/assets/stylesheets/sage/core/_typography.scss
  app/assets/stylesheets/sage/core/_variables.scss
  app/assets/stylesheets/sage/patterns/elements/_checkbox.scss
  app/assets/stylesheets/sage/patterns/elements/_radio.scss
  app/assets/stylesheets/sage/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/patterns/elements/_tooltip.scss
  app/assets/stylesheets/sage/tokens/_font_height.scss
  app/assets/stylesheets/sage/tokens/_font_size.scss
  app/assets/stylesheets/sage/tokens/_font_weight.scss
  app/assets/stylesheets/sage/tokens/_letter_spacing.scss
  app/assets/stylesheets/sage/tokens/_line_height.scss
  app/assets/stylesheets/sage/vendor/_reboot.scss
  app/assets/stylesheets/sage_docs.css.scss
  app/assets/stylesheets/sage_docs/_example.scss
  app/assets/stylesheets/sage_docs/_quick_links.scss
  app/assets/stylesheets/sage_docs/_specs.scss
  app/assets/stylesheets/sage_docs/_token.scss
  app/helpers/sage/tokens_helper.rb
  app/views/layouts/sage/application.html.erb
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/elements/_element_preview.html.erb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/examples/objects/_object_preview.html.erb
  app/views/sage/examples/utilities/_utility.html.erb
  app/views/sage/pages/color.html.erb
  app/views/sage/pages/container.html.erb
  app/views/sage/pages/elements.html.erb
  app/views/sage/pages/grid.html.erb
  app/views/sage/pages/index.html.erb
  app/views/sage/pages/objects.html.erb
  app/views/sage/pages/status.html.erb
  app/views/sage/pages/token.html.erb
  app/views/sage/pages/typography.html.erb
  lib/generators/sage_page/templates/page.html.erb
Labels: Review, priority

#114 adding gems
  Gemfile
  app/views/sage/application/_assistant.html.erb
  lib/sage/engine.rb
  sage.gemspec
Labels: Review

#110 Realign switch styles
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/switch/_preview.html.erb
  app/views/sage/examples/elements/switch/_props.html.erb
  app/views/sage/examples/elements/switch/_rules_do.html.erb
  app/views/sage/examples/elements/switch/_rules_dont.html.erb
Labels: Review, thumbsup

#118 bumping version to 6
  lib/sage/version.rb
Labels: Review

#91 Add live profile card
  app/assets/javascripts/sage/sage_docs.js
  app/assets/stylesheets/sage/docs/_quick_links.scss
  app/assets/stylesheets/sage/sage_docs.css.scss
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_icons.scss
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/assets/stylesheets/sage/system/core/_typography.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_active_mic.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_option_menu.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_profile_card.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_user_control.scss
  app/assets/stylesheets/sage/system/tokens/_color_palette.scss
  app/assets/stylesheets/sage/system/tokens/_z_index.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/elements/_element_preview.html.erb
  app/views/sage/examples/objects/_object.html.erb
  app/views/sage/examples/objects/_object_preview.html.erb
  app/views/sage/examples/objects/live_avatar/_preview.html.erb
  app/views/sage/examples/objects/live_avatar/_props.html.erb
  app/views/sage/examples/objects/live_avatar/_rules_do.html.erb
  app/views/sage/examples/objects/live_avatar/_rules_dont.html.erb
  app/views/sage/examples/objects/live_option_menu/_preview.html.erb
  app/views/sage/examples/objects/live_option_menu/_props.html.erb
  app/views/sage/examples/objects/live_option_menu/_rules_do.html.erb
  app/views/sage/examples/objects/live_option_menu/_rules_dont.html.erb
  app/views/sage/examples/objects/live_profile_card/_preview.html.erb
  app/views/sage/examples/objects/live_profile_card/_props.html.erb
  app/views/sage/examples/objects/live_profile_card/_rules_do.html.erb
  app/views/sage/examples/objects/live_profile_card/_rules_dont.html.erb
  app/views/sage/examples/objects/live_user_control/_preview.html.erb
  app/views/sage/examples/objects/live_user_control/_props.html.erb
  app/views/sage/examples/objects/live_user_control/_rules_do.html.erb
  app/views/sage/examples/objects/live_user_control/_rules_dont.html.erb
  app/views/sage/pages/color.html.erb
  app/views/sage/pages/container.html.erb
  app/views/sage/pages/elements.html.erb
  app/views/sage/pages/objects.html.erb
  app/views/sage/pages/status.html.erb
  app/views/sage/pages/token.html.erb
  app/views/sage/pages/typography.html.erb
  app/views/sage/pages/utilities.html.erb
Labels: Review

#96 Text areas
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
  app/helpers/sage/elements_helper.rb
  app/helpers/sage/tokens_helper.rb
  app/views/sage/examples/elements/form_input/_props.html.erb
  app/views/sage/examples/elements/form_input/_rules_do.html.erb
  app/views/sage/examples/elements/form_textarea/_preview.html.erb
  app/views/sage/examples/elements/form_textarea/_props.html.erb
  app/views/sage/examples/elements/form_textarea/_rules_do.html.erb
  app/views/sage/examples/elements/form_textarea/_rules_dont.html.erb
Labels: Review, thumbsup

#115 Update with new type specs
  app/assets/stylesheets/sage/system/core/_typography.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_checkbox.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_radio.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/system/patterns/elements/_tooltip.scss
  app/assets/stylesheets/sage/system/patterns/objects/_banner.scss
  app/assets/stylesheets/sage/system/patterns/objects/_nav.scss
  app/assets/stylesheets/sage/system/patterns/objects/_tabs.scss
  app/assets/stylesheets/sage/system/tokens/_color_palette.scss
  app/assets/stylesheets/sage/system/vendor/_reboot.scss
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/application/_sidebar_elements.html.erb
  app/views/sage/application/_sidebar_objects.html.erb
  app/views/sage/application/_sidebar_styles.html.erb
  app/views/sage/examples/elements/button/_preview.html.erb
  app/views/sage/examples/elements/danger_button/_preview.html.erb
  app/views/sage/examples/elements/icon_button/_preview.html.erb
  app/views/sage/examples/elements/tooltip/_preview.html.erb
  app/views/sage/examples/objects/banner/_preview.html.erb
  app/views/sage/examples/objects/nav/_preview.html.erb
Labels: Review, thumbsup

#121 Viewport metatag missing for mobile devices
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
  app/views/layouts/sage/application.html.erb
  app/views/layouts/sage/breakout.html.erb
  test/dummy/app/views/layouts/application.html.erb
Labels: Review

#120 Fixes for prep to version bump
  .ruby-version
  app/assets/javascripts/sage/sage_docs.js
  app/assets/javascripts/sage/system/tooltip.js
  app/assets/stylesheets/sage/docs/_colors.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
  app/views/sage/examples/objects/sidebar/_preview.html.erb
  app/views/sage/pages/color.html.erb
Labels: Review

#116 Replace calculated `rem` values with rem function
  app/assets/stylesheets/sage/docs/_example.scss
  app/assets/stylesheets/sage/docs/_variables.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_menu_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_radio.scss
  app/assets/stylesheets/sage/system/patterns/elements/_tooltip.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_avatar.scss
  app/assets/stylesheets/sage/system/tokens/_border.scss
  app/assets/stylesheets/sage/system/tokens/_font_size.scss
  app/assets/stylesheets/sage/system/tokens/_letter_spacing.scss
  app/assets/stylesheets/sage/system/tokens/_sidebar.scss
  app/assets/stylesheets/sage/system/tokens/_spacing.scss
  app/helpers/sage/tokens_helper.rb
Labels: Review, thumbsup

#123 [mobile] Form field drop shadows
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
Labels: Review, mobile, thumbsup

#125 [mobile] Radio button animation
  app/assets/stylesheets/sage/system/patterns/elements/_radio.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/radio/_preview.html.erb
  app/views/sage/examples/elements/radio/_props.html.erb
  app/views/sage/examples/elements/radio/_rules_do.html.erb
  app/views/sage/examples/elements/radio/_rules_dont.html.erb
  app/views/sage/examples/elements/switch/_rules_do.html.erb
  app/views/sage/examples/elements/switch/_rules_dont.html.erb
Labels: Review, mobile

#126 [mobile] Switch element outline
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
Labels: Review, mobile, thumbsup

#101 Labels
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_label.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/label/_preview.html.erb
  app/views/sage/examples/elements/label/_props.html.erb
  app/views/sage/examples/elements/label/_rules_do.html.erb
  app/views/sage/examples/elements/label/_rules_dont.html.erb
Labels: Review

#131 Label Code Status Quick Fix
  app/helpers/sage/elements_helper.rb
Labels: Review, documentation

#128 Checkbox error styles
  app/assets/stylesheets/sage/system/patterns/elements/_checkbox.scss
  app/views/sage/examples/elements/checkbox/_preview.html.erb
Labels: Review

#132 Update npm dependencies
  package-lock.json
Labels: Review
