Repository Kajabi/sage, pull requests merged in 2020-05, with the labels that each got.

#217 Base PR template
  .github/pull_request_template.md
Labels: Review, documentation

#219 Convert card markup to .erb
  app/views/sage/examples/objects/card/_markup.html.erb
  app/views/sage/examples/objects/card/_preview.html.erb
Labels: Review

#215 Icon sizing in buttons
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/examples/elements/button/_markup.html.erb
  app/views/sage/examples/elements/button/_preview.html.erb
  app/views/sage/examples/elements/danger_button/_markup.html.erb
  app/views/sage/examples/elements/danger_button/_preview.html.erb
  app/views/sage/examples/elements/danger_button/_props.html.erb
  app/views/sage/examples/elements/danger_button/_rules_do.html.erb
  app/views/sage/examples/elements/danger_button/_rules_dont.html.erb
Labels: Review, thumbsup

#225 Convert tabs markup to .erb
  app/views/sage/examples/objects/tabs/_markup.html.erb
  app/views/sage/examples/objects/tabs/_preview.html.erb
Labels: Review

#226 Live stream updates
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_control.scss
  app/assets/stylesheets/sage/system/patterns/objects/_live_stream_video_grid.scss
  app/views/sage/examples/objects/live_stream_video_grid/_preview.html.erb
Labels: Review

#218 Stylelint fixes
  .stylelintrc.json
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_select.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/system/patterns/objects/_billboard.scss
Labels: Review, low priority, thumbsup

#228 Convert description markup to .erb
  app/views/sage/examples/elements/description/_markup.html.erb
  app/views/sage/examples/elements/description/_preview.html.erb
Labels: Review

#229 Convert form section markup to .erb
  app/views/sage/examples/objects/form_section/_markup.html.erb
  app/views/sage/examples/objects/form_section/_preview.html.erb
Labels: Review

#230 Update alert so closing is optional
  app/views/sage/examples/objects/alert/_markup.html.erb
  app/views/sage/examples/objects/alert/_preview.html.erb
  app/views/sage/examples/objects/form_section/_markup.html.erb
Labels: Review

#232 Convert nav markup to .erb
  app/views/sage/examples/objects/nav/_markup.html.erb
  app/views/sage/examples/objects/nav/_preview.html.erb
Labels: Review

#186 Table column options
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/elements/table/_markup.html.erb
  app/views/sage/examples/elements/table/_preview.html.erb
Labels: Review

#233 HTML Validation cleanup
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/elements/switch/_preview.html.erb
  app/views/sage/pages/icon.html.erb
Labels: Review, a11y, thumbsup

#234 Convert sidebar markup to .erb
  app/views/sage/examples/objects/nav/_markup.html.erb
  app/views/sage/examples/objects/nav/_preview.html.erb
  app/views/sage/examples/objects/sidebar/_markup.html.erb
  app/views/sage/examples/objects/sidebar/_preview.html.erb
Labels: Review, thumbsup

#238 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue.md
Labels: Review, documentation

#241 Convert live active mic markup to .erb
  app/views/sage/examples/objects/live_active_mic/_markup.html.erb
  app/views/sage/examples/objects/live_active_mic/_preview.html.erb
Labels: Review

#239 Convert page heading markup to .erb
  app/views/sage/examples/objects/page_heading/_markup.html.erb
  app/views/sage/examples/objects/page_heading/_preview.html.erb
Labels: Review

#240 Convert panel markup to .erb
  app/views/sage/examples/objects/panel/_markup.html.erb
  app/views/sage/examples/objects/panel/_preview.html.erb
Labels: Review

#242 Convert form select markup to .erb
  app/views/sage/examples/elements/form_select/_markup.html.erb
  app/views/sage/examples/elements/form_select/_preview.html.erb
Labels: Review

#243 Convert pagination markup to .erb
  app/assets/stylesheets/sage/system/patterns/objects/_pagination.scss
  app/views/sage/examples/objects/pagination/_markup.html.erb
  app/views/sage/examples/objects/pagination/_preview.html.erb
Labels: Review

#246 Convert link_button markup to .erb
  app/views/sage/examples/elements/link_button/_markup.html.erb
  app/views/sage/examples/elements/link_button/_preview.html.erb
Labels: in progress

#244 Table column options
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/assets/javascripts/sage/system/table.js
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/elements/table/_markup.html.erb
  app/views/sage/examples/elements/table/_preview.html.erb
  app/views/sage/examples/elements/table/_props.html.erb
  app/views/sage/examples/elements/table/_rules_do.html.erb
Labels: Review

#248 Update card image path
  app/views/sage/examples/objects/card/_markup.html.erb
  app/views/sage/examples/objects/card/_preview.html.erb
Labels: Review

#249 Correct image paths & optimizations
  app/assets/images/sage/avatar/alex.png
  app/assets/images/sage/avatar/chanel.png
  app/assets/images/sage/avatar/cj.png
  app/assets/images/sage/avatar/court.png
  app/assets/images/sage/avatar/forrest.png
  app/assets/images/sage/avatar/isabelle.png
  app/assets/images/sage/avatar/jay.png
  app/assets/images/sage/avatar/jj.png
  app/assets/images/sage/avatar/lienha.png
  app/assets/images/sage/avatar/phil.png
  app/assets/images/sage/avatar/sean.png
  app/assets/images/sage/billboard/background_1.jpg
  app/assets/images/sage/billboard/background_2.jpg
  app/assets/images/sage/billboard/background_3.jpg
  app/assets/images/sage/billboard/background_4.jpg
  app/views/sage/examples/objects/live_avatar/_markup.html.erb
  app/views/sage/examples/objects/live_avatar/_preview.html.erb
  app/views/sage/examples/objects/live_profile_card/_preview.html.erb
  app/views/sage/examples/objects/live_stream_video_grid/_preview.html.erb
Labels: Review

#247 Shortened code previews
  app/assets/javascripts/sage/docs/example.js
  app/assets/javascripts/sage/sage_docs.js
  app/assets/stylesheets/sage/docs/_example.scss
  app/assets/stylesheets/sage/system/core/_mixins.scss
  app/views/sage/examples/elements/_element.html.erb
  app/views/sage/examples/objects/_object.html.erb
Labels: Review, documentation, enhancement, thumbsup

#252 Table column visibility
  app/assets/stylesheets/sage/system/patterns/elements/_table.scss
  app/views/sage/examples/elements/table/_preview.html.erb
Labels: Review, thumbsup

#245 Super_Admin Simpleform Compatibility Followup
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/assets/javascripts/sage/system/select.js
  app/assets/javascripts/sage/system/util.js
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_select.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_textarea.scss
  app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
  app/assets/stylesheets/sage/system/patterns/objects/_form_section.scss
  app/assets/stylesheets/sage/system/patterns/objects/_panel.scss
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/elements/button/_markup.html.erb
  app/views/sage/examples/elements/button/_preview.html.erb
  app/views/sage/examples/elements/form_select/_markup.html.erb
  app/views/sage/examples/elements/form_select/_preview.html.erb
  app/views/sage/examples/objects/panel/_markup.html.erb
Labels: Review

#257 Convert nav object to an unordered list
  app/assets/stylesheets/sage/system/patterns/objects/_nav.scss
  app/views/sage/application/_sidebar.html.erb
  app/views/sage/application/_sidebar_elements.html.erb
  app/views/sage/application/_sidebar_objects.html.erb
  app/views/sage/application/_sidebar_styles.html.erb
  app/views/sage/examples/objects/nav/_markup.html.erb
Labels: Review

#104 Password masking
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/assets/javascripts/sage/system/inputgroup.js
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
  app/assets/stylesheets/sage/system/patterns/objects/_input_group.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/elements/form_input/_markup.html.erb
  app/views/sage/examples/elements/form_input/_preview.html.erb
  app/views/sage/examples/elements/form_input/_props.html.erb
  app/views/sage/examples/elements/form_input/_rules_do.html.erb
  app/views/sage/examples/elements/form_input/_rules_dont.html.erb
  app/views/sage/examples/objects/input_group/_markup.html.erb
  app/views/sage/examples/objects/input_group/_preview.html.erb
  app/views/sage/examples/objects/input_group/_props.html.erb
  app/views/sage/examples/objects/input_group/_rules_do.html.erb
  app/views/sage/examples/objects/input_group/_rules_dont.html.erb
Labels: Review, enhancement

#260 [BUG] Form section styles not applied
  app/views/sage/examples/objects/form_section/_markup.html.erb
Labels: Review, bug :space_invader:, thumbsup

#262 Tooltip element revisions
  app/assets/javascripts/sage/system/tooltip.js
  app/assets/stylesheets/sage/system/core/_variables.scss
  app/assets/stylesheets/sage/system/patterns/elements/_tooltip.scss
  app/views/sage/examples/elements/tooltip/_markup.html.erb
  app/views/sage/examples/elements/tooltip/_preview.html.erb
  app/views/sage/examples/elements/tooltip/_props.html.erb
Labels: Review, documentation, enhancement, thumbsup

#263 Meter element
  app/assets/javascripts/sage/docs/meter.js
  app/assets/javascripts/sage/sage_docs.js
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/assets/javascripts/sage/system/meter.js
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/elements/_meter.scss
  app/helpers/sage/elements_helper.rb
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/elements/meter/_markup.html.erb
  app/views/sage/examples/elements/meter/_preview.html.erb
  app/views/sage/examples/elements/meter/_props.html.erb
  app/views/sage/examples/elements/meter/_rules_do.html.erb
  app/views/sage/examples/elements/meter/_rules_dont.html.erb
Labels: Review, enhancement, thumbsup

#266 Warning clean up
  app/assets/stylesheets/sage/system/patterns/elements/_button.scss
  app/assets/stylesheets/sage/system/patterns/elements/_form_select.scss
  app/assets/stylesheets/sage/system/patterns/objects/_panel.scss
Labels: Review

#261 Password tooltip
  app/assets/javascripts/lib/zxcvbn.js
  app/assets/javascripts/sage/docs/inputhelper.js
  app/assets/javascripts/sage/sage_docs.js
  app/assets/javascripts/sage/sage_system.js
  app/assets/javascripts/sage/system/init.js
  app/assets/javascripts/sage/system/inputgroup.js
  app/assets/javascripts/sage/system/inputhelper.js
  app/assets/javascripts/sage/system/util.js
  app/assets/stylesheets/sage/sage_system.css.scss
  app/assets/stylesheets/sage/system/patterns/elements/_meter.scss
  app/assets/stylesheets/sage/system/patterns/objects/_input_group.scss
  app/assets/stylesheets/sage/system/patterns/objects/_input_helper.scss
  app/helpers/sage/objects_helper.rb
  app/views/sage/application/_scripts.html.erb
  app/views/sage/examples/objects/input_group/_markup.html.erb
  app/views/sage/examples/objects/input_group/_preview.html.erb
  app/views/sage/examples/objects/input_helper/_markup.html.erb
  app/views/sage/examples/objects/input_helper/_preview.html.erb
  app/views/sage/examples/objects/input_helper/_props.html.erb
  app/views/sage/examples/objects/input_helper/_rules_do.html.erb
  app/views/sage/examples/objects/input_helper/_rules_dont.html.erb
Labels: Needs design input, Review, enhancement

#269 Fix broken spacing for sage-select
  app/assets/stylesheets/sage/system/patterns/elements/_form_select.scss
Labels: Review, bug :space_invader:
