Repository Kajabi/sage, pull requests merged in 2020-08, with the labels that each got.

#361 Sage System design review sizing adjustments
  .gitignore
  app/views/examples/elements/_element_preview.html.erb
  app/views/examples/objects/_object_preview.html.erb
  app/views/examples/objects/card/_props.html.erb
  app/views/examples/objects/modal/_markup.html.erb
  lib/sage-frontend/stylesheets/docs/_icon.scss
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_checkbox.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_select.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_status_icon.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage-frontend/stylesheets/system/tokens/_spacing.scss
Labels: Review

#363 Documentation typo fixes
  app/views/pages/color.html.erb
  app/views/pages/typography.html.erb
Labels: documentation, good first issue

#362 Migrate Sage Generators
  lib/generators/sage_element/USAGE
  lib/generators/sage_element/sage_element_generator.rb
  lib/generators/sage_element/templates/markup.html.erb
  lib/generators/sage_element/templates/props.html.erb
  lib/generators/sage_element/templates/rules_do.html.erb
  lib/generators/sage_element/templates/rules_dont.html.erb
  lib/generators/sage_element/templates/style.scss
  lib/generators/sage_object/USAGE
  lib/generators/sage_object/sage_object_generator.rb
  lib/generators/sage_object/templates/markup.html.erb
  lib/generators/sage_object/templates/props.html.erb
  lib/generators/sage_object/templates/rules_do.html.erb
  lib/generators/sage_object/templates/rules_dont.html.erb
  lib/generators/sage_object/templates/style.scss
  lib/generators/sage_page/USAGE
  lib/generators/sage_page/sage_page_generator.rb
  lib/generators/sage_page/templates/page.html.erb
  lib/generators/sage_token/USAGE
  lib/generators/sage_token/sage_token_generator.rb
  lib/generators/sage_token/templates/style.scss
  lib/generators/sage_utility/USAGE
  lib/generators/sage_utility/sage_utility_generator.rb
  lib/generators/sage_utility/templates/markup.html.erb
  lib/generators/sage_utility/templates/style.scss
  lib/sage-engine/generators/sage_element/templates/markup.html.erb
  lib/sage-engine/generators/sage_object/templates/markup.html.erb
  lib/sage-engine/generators/sage_page/templates/page.html.erb
  lib/sage-engine/generators/sage_utility/templates/markup.html.erb
  package.json
Labels: Review, documentation

#364 Lint With CircleCI
  .circleci/config.yml
  package.json
Labels: Review

#365 Add system-styles file
  lib/sage-frontend/packs/system-styles.js
Labels: Review, enhancement

#366 Converts positioning of affix to fix value
  lib/sage-frontend/stylesheets/system/patterns/elements/_form_input.scss
Labels: Review, bug :space_invader:

#367 Add newline in system-styles.js
  lib/sage-frontend/packs/system-styles.js
Labels: Review, bug :space_invader:, priority

#368 Add modal container token to docs and update spacing
  app/helpers/tokens_helper.rb
  lib/sage-frontend/stylesheets/docs/_token.scss
Labels: Review, documentation

#370 Update icons
  app/views/pages/icon.html.erb
  lib/sage-frontend/fonts/sage/Sage.eot
  lib/sage-frontend/fonts/sage/Sage.svg
  lib/sage-frontend/fonts/sage/Sage.ttf
  lib/sage-frontend/fonts/sage/Sage.woff
  lib/sage-frontend/stylesheets/system/tokens/_icon.scss
Labels: Icon, Review

#371 Space HelpLink when in Page Heading
  lib/sage-frontend/stylesheets/system/patterns/elements/_link.scss
Labels: Review

#372 Update loader
  app/views/examples/elements/loader/_markup.html.erb
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_loader.scss
Labels: enhancement

#369 [MAN-365] Sage Tabs with style and stacked options
  app/helpers/elements_helper.rb
  app/views/examples/elements/choice/_markup.html.erb
  app/views/examples/elements/choice/_preview.html.erb
  app/views/examples/elements/choice/_props.html.erb
  app/views/examples/elements/choice/_rules_do.html.erb
  app/views/examples/elements/choice/_rules_dont.html.erb
  app/views/examples/elements/tab/_markup.html.erb
  app/views/examples/elements/tab/_preview.html.erb
  app/views/examples/elements/tab/_props.html.erb
  app/views/examples/elements/tab/_rules_do.html.erb
  app/views/examples/elements/tab/_rules_dont.html.erb
  app/views/examples/objects/tabs/_markup.html.erb
  app/views/examples/objects/tabs/_preview.html.erb
  app/views/examples/objects/tabs/_props.html.erb
  lib/sage-frontend/javascript/system/tabs.js
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
Labels: Review, enhancement

#373 Update panels with 🍬
  app/views/examples/objects/panel/_markup.html.erb
  app/views/examples/objects/panel/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
Labels: Review

#374 Progress style tabs and breadcrumbs 🍞
  app/views/examples/elements/breadcrumbs/_markup.html.erb
  app/views/examples/elements/breadcrumbs/_preview.html.erb
  app/views/examples/objects/tabs/_markup.html.erb
  app/views/examples/objects/tabs/_preview.html.erb
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
  lib/sage-frontend/stylesheets/system/tokens/_spacing.scss
Labels: Review, enhancement

#376 Merge system into docs asset indexes
  app/views/application/_scripts.html.erb
  app/views/application/_styles.html.erb
  app/views/pages/index.html.erb
  lib/sage-frontend/packs/docs.js
  lib/sage-frontend/stylesheets/docs/_theme.scss
  lib/sage-frontend/stylesheets/docs/index.scss
Labels: bug :space_invader:, documentation

#377 Downgrade spring to match Product's version
  Gemfile
  Gemfile.lock
Labels: dependencies

#375 Add styles to support upload cards
  app/helpers/elements_helper.rb
  app/views/examples/elements/button/_markup.html.erb
  app/views/examples/elements/icon_card/_markup.html.erb
  app/views/examples/elements/icon_card/_preview.html.erb
  app/views/examples/elements/icon_card/_props.html.erb
  app/views/examples/elements/icon_card/_rules_do.html.erb
  app/views/examples/elements/icon_card/_rules_dont.html.erb
  app/views/examples/elements/label/_markup.html.erb
  app/views/examples/elements/label/_preview.html.erb
  app/views/examples/objects/card/_markup.html.erb
  app/views/examples/objects/card/_preview.html.erb
  app/views/pages/color.html.erb
  lib/sage-frontend/stylesheets/system/core/_functions.scss
  lib/sage-frontend/stylesheets/system/core/_icons.scss
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_icon_card.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/tokens/_color_combos.scss
  lib/sage-frontend/stylesheets/system/utilities/_spacer.scss
Labels: Review, enhancement

#378 Icon list
  app/helpers/objects_helper.rb
  app/views/examples/objects/icon_list/_markup.html.erb
  app/views/examples/objects/icon_list/_preview.html.erb
  app/views/examples/objects/icon_list/_props.html.erb
  app/views/examples/objects/icon_list/_rules_do.html.erb
  app/views/examples/objects/icon_list/_rules_dont.html.erb
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_checkbox.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_radio.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_icon_list.scss
Labels: Review, enhancement

#382 Sync Radio buttons with spec
  lib/sage-frontend/stylesheets/system/core/_variables.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_radio.scss
Labels: Review

#379 [BUG] Input group button height
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_input_group.scss
Labels: Review, regression

#384 Sage Lists
  app/helpers/elements_helper.rb
  app/views/examples/elements/lists/_preview.html.erb
  app/views/examples/elements/lists/_props.html.erb
  app/views/examples/elements/lists/_rules_do.html.erb
  app/views/examples/elements/lists/_rules_dont.html.erb
  app/views/examples/objects/panel/_preview.html.erb
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_checkbox.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_label.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_lists.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_radio.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_switch.scss
Labels: enhancement

#386 [BUG] Code status page displays an error
  app/helpers/elements_helper.rb
  app/helpers/objects_helper.rb
Labels: Review, bug :space_invader:

#333 Update quick link pseudo-states
  lib/sage-frontend/stylesheets/docs/_quick_links.scss
Labels: Review, enhancement, low priority

#387 Stacked Tab Choice Button Layout Issue - Safari
  lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
Labels: bug :space_invader:

#385 Update Inter font from v3.12 to 3.14
  lib/sage-frontend/fonts/inter/Inter-Black.woff
  lib/sage-frontend/fonts/inter/Inter-Black.woff2
  lib/sage-frontend/fonts/inter/Inter-BlackItalic.woff
  lib/sage-frontend/fonts/inter/Inter-BlackItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-Bold.woff
  lib/sage-frontend/fonts/inter/Inter-Bold.woff2
  lib/sage-frontend/fonts/inter/Inter-BoldItalic.woff
  lib/sage-frontend/fonts/inter/Inter-BoldItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-ExtraBold.woff
  lib/sage-frontend/fonts/inter/Inter-ExtraBold.woff2
  lib/sage-frontend/fonts/inter/Inter-ExtraBoldItalic.woff
  lib/sage-frontend/fonts/inter/Inter-ExtraBoldItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-ExtraLight.woff
  lib/sage-frontend/fonts/inter/Inter-ExtraLight.woff2
  lib/sage-frontend/fonts/inter/Inter-ExtraLightItalic.woff
  lib/sage-frontend/fonts/inter/Inter-ExtraLightItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-Italic.woff
  lib/sage-frontend/fonts/inter/Inter-Italic.woff2
  lib/sage-frontend/fonts/inter/Inter-Light.woff
  lib/sage-frontend/fonts/inter/Inter-Light.woff2
  lib/sage-frontend/fonts/inter/Inter-LightItalic.woff
  lib/sage-frontend/fonts/inter/Inter-LightItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-Medium.woff
  lib/sage-frontend/fonts/inter/Inter-Medium.woff2
  lib/sage-frontend/fonts/inter/Inter-MediumItalic.woff
  lib/sage-frontend/fonts/inter/Inter-MediumItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-Regular.woff
  lib/sage-frontend/fonts/inter/Inter-Regular.woff2
  lib/sage-frontend/fonts/inter/Inter-SemiBold.woff
  lib/sage-frontend/fonts/inter/Inter-SemiBold.woff2
  lib/sage-frontend/fonts/inter/Inter-SemiBoldItalic.woff
  lib/sage-frontend/fonts/inter/Inter-SemiBoldItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-Thin.woff
  lib/sage-frontend/fonts/inter/Inter-Thin.woff2
  lib/sage-frontend/fonts/inter/Inter-ThinItalic.woff
  lib/sage-frontend/fonts/inter/Inter-ThinItalic.woff2
  lib/sage-frontend/fonts/inter/Inter-italic.var.woff2
  lib/sage-frontend/fonts/inter/Inter-roman.var.woff2
  lib/sage-frontend/fonts/inter/Inter.var.woff2
  lib/sage-frontend/stylesheets/system/core/_fonts.scss
Labels: Review, enhancement

#390 Modal Bugfix: Safari Animation
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
Labels: bug :space_invader:

#391 Bugfix: modal blur does not dismiss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
Labels: bug :space_invader:

#392 Jcm remove utilities
  app/helpers/utilities_helper.rb
  app/views/application/_sidebar.html.erb
  app/views/examples/utilities/media/_preview.html.erb
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/utilities/_media.scss
Labels: Review

#389 [BUG] Objects nav link in the sidebar scrolls to bottom of page
  lib/sage-frontend/javascript/system/tabs.js
Labels: bug :space_invader:

#394 sidebar order
  app/views/application/_assistant.html.erb
  app/views/application/_sidebar.html.erb
Labels: Review

#395 Address Sidebar Conflict Comments
  app/views/application/_sidebar.html.erb
Labels: bug :space_invader:

#393 Panel adjustments
  app/views/examples/objects/panel/_markup.html.erb
  app/views/examples/objects/panel/_preview.html.erb
  app/views/examples/objects/panel/_rules_do.html.erb
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/core/_typography.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
Labels: enhancement

#396 [BUG] Index image breaks out of container on smaller screens
  app/views/pages/index.html.erb
Labels: bug :space_invader:, documentation

#397 Updates to Dropdown
  app/helpers/elements_helper.rb
  app/views/examples/elements/search/_markup.html.erb
  app/views/examples/elements/search/_preview.html.erb
  app/views/examples/elements/search/_props.html.erb
  app/views/examples/elements/search/_rules_do.html.erb
  app/views/examples/elements/search/_rules_dont.html.erb
  app/views/examples/objects/dropdown/_markup.html.erb
  app/views/examples/objects/dropdown/_preview.html.erb
  lib/sage-frontend/javascript/system/dropdown.js
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_search.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
Labels: Review, enhancement

#383 [BUG] Switch/checkbox/radio error state styling
  app/views/examples/elements/radio/_markup.html.erb
  app/views/examples/elements/radio/_preview.html.erb
  lib/sage-frontend/stylesheets/system/patterns/elements/_checkbox.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_radio.scss
  lib/sage-frontend/stylesheets/system/patterns/elements/_switch.scss
Labels: Review, bug :space_invader:

#399 Migrate x-padding from SageContainer to SageContent
  lib/sage-frontend/stylesheets/system/layout/_container.scss
  lib/sage-frontend/stylesheets/system/layout/_content.scss
Labels: Review, kajabi

#400 Add Upload Card object
  app/helpers/objects_helper.rb
  app/views/examples/objects/upload_card/_markup.html.erb
  app/views/examples/objects/upload_card/_preview.html.erb
  app/views/examples/objects/upload_card/_props.html.erb
  app/views/examples/objects/upload_card/_rules_do.html.erb
  app/views/examples/objects/upload_card/_rules_dont.html.erb
  lib/sage-frontend/stylesheets/system/_consumables.scss
  lib/sage-frontend/stylesheets/system/core/_mixins.scss
  lib/sage-frontend/stylesheets/system/index.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_card.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
  lib/sage-frontend/stylesheets/system/patterns/objects/_upload_card.scss
  lib/sage-frontend/stylesheets/system/tokens/_index.scss
Labels: enhancement
